---
development:
  dialect: "sqlite3"
  database: /home/benfleming/go/src/github.com/benjamesfleming/gotasks_gotasks_development.sqlite

test:
  dialect: "sqlite3"
  database: /home/benfleming/go/src/github.com/benjamesfleming/gotasks_gotasks_test.sqlite

production:
  dialect: "sqlite3"
  database: /home/benfleming/go/src/github.com/benjamesfleming/gotasks_gotasks_production.sqlite
