---
development:
  dialect: "sqlite3"
  database: "{{ env "PWD" }}/tmp/database_dev.sqlite3"

test:
  dialect: "sqlite3"
  database: "{{ env "PWD" }}/tmp/database_test.sqlite3"

production:
  dialect: "sqlite3"
  database: "{{ env "PWD" }}/tmp/database.sqlite3"
