# Global Config
#   `env` the run mode ("development", "production") (default: "production")
env = "production"

# Server Config
#   `port` the http listen port (default: "3000")
#   `bind` the interface to bind to (default: "0.0.0.0")
#   `host` the publicly routable host name (default: "http://127.0.0.1:3000")
#   `avatar-dir` the directory to save the user avatars to
#   `unique-key` must be 64 bytes
[server]
port = "3000"
bind = "0.0.0.0"
host = "http://127.0.0.1:3000"
avatar-dir = "./avatars"
unique-key = "{{ . }}" # generated on install

# Database Config
#   `type` the type of database ("sqlite3", "mysql") (default: "sqlite3")
#   `connection` the connection string of the database (default: "./database.db")
#
# IMPORTANT: When using `mysql` database the connection string must take the following format:
#   "username:password@(host)/database?charset=utf8&parseTime=True&loc=Local"
[database]
type = "sqlite3"
connection = "./database.db"

# Auth Config
#   `gravatar` ("all", "fallback", "none") (default: "none")
#       "all" to use Gravatar for all accounts
#       "fallback" to use Gravatar only when no avatar is provided
#       "none" disable Gravatar usage
#
# Auth Provider Config
#   `enabled` if the given provider is enabled (default: false)
#   `client-id` the id provided by the provider
#   `secret` the secret provided by the provider
[auth]
gravatar = "none"

    [auth.github]
    enabled = false
    client-id = ""
    secret = ""

    [auth.google]
    enabled = false
    client-id = ""
    secret = ""