name: Go
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get github.com/GeertJohan/go.rice/rice 
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build for linux
      run: |
        rice embed-go
        go build -o build/gotasks-linux-x64 server.go
    
    - name: Build for windows
      run: |
        rice embed-go
        GOOS=windows GOARCH=386 go build -o build/gotasks-win64.exe server.go
      
    - name: Upload linux artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: gotasks-linux-x64
        path: build/gotasks-linux-x64
        
    - name: Upload windows artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: gotasks-win64.exe
        path: build/build/gotasks-win64.exe  
